### ISSUE TITLE
这几种模型预测的准确率如何

### ISSUE THREAD

**Issue by delltower** [ewanlee/video_title_classification#1]
hi, 我的资源不多,想使用一个模型去训练,这几个模型的准确率如何,差别是怎样的

**Comment by ewanlee** [comment]
抱歉现在才看到，TextCNN效果最好，另外三个算法之间性能差别不是很大，与TextCNN相比也不是很大，大概在几个百分点

**Comment by ewanlee** [comment]
@delltower 抱歉现在才看到，TextCNN效果最好，另外三个算法之间性能差别不是很大，与TextCNN相比差距也不是很大，大概在几个百分点
